import { Component, OnInit, inject } from '@angular/core';
import { CommonModule, AsyncPipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { LucideAngularModule, LucideBox, LucidePlus, LucideSearch } from 'lucide-angular';
import { NgbPagination, NgbPaginationNext, NgbPaginationPrevious, NgbTooltipModule } from '@ng-bootstrap/ng-bootstrap';
import { TableService } from '@core/services/table.service';
import { Router } from '@angular/router';
import { NgIcon } from '@ng-icons/core';
import { Observable } from 'rxjs';

export interface DiagGroupType {
  ID: number;
  DiagGroupID: number;
  DiagGroupName: string;
  DiagTestID: number;
  DiagTestName: string;
  DiagTestType: string;
  ReportingPriority: number;
  Notes?: string;
  BranchID: number;
  DepartmentID?: number;
  CreatedStaffID?: string;
  CreatedDateTime?: string;
  UpdatedStaffID?: string;
  UpdatedDateTime?: string;
  IsRowDeleted: string;
  [key: string]: any;
}

export const DIAG_GROUP_DATA: DiagGroupType[] = [
  {
    "ID": 10094,
    "DiagGroupID": 8,
    "DiagGroupName": "GTT / OGTT (3 Hrs Oral Glucose Tolerance Test",
    "DiagTestID": 1,
    "DiagTestName": "1 Time GRBS (Glucometer RBS)",
    "DiagTestType": "SNG",
    "ReportingPriority": 1,
    "Notes": "Initial screening test",
    "BranchID": 1,
    "DepartmentID": 10,
    "CreatedStaffID": "1",
    "CreatedDateTime": "2024-04-24 10:30:00",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2024-04-24 10:30:00",
    "IsRowDeleted": "N"
  },
  {
    "ID": 10095,
    "DiagGroupID": 8,
    "DiagGroupName": "GTT / OGTT (3 Hrs Oral Glucose Tolerance Test",
    "DiagTestID": 4,
    "DiagTestName": "2 Time GRBS (Glucometer RBS)",
    "DiagTestType": "SNG",
    "ReportingPriority": 2,
    "Notes": "Second hour check",
    "BranchID": 1,
    "DepartmentID": 10,
    "CreatedStaffID": "1",
    "CreatedDateTime": "2024-04-24 10:30:00",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2024-04-24 10:30:00",
    "IsRowDeleted": "N"
  },
  {
    "ID": 10096,
    "DiagGroupID": 8,
    "DiagGroupName": "GTT / OGTT (3 Hrs Oral Glucose Tolerance Test",
    "DiagTestID": 9,
    "DiagTestName": "3 Time GRBS (Glucometer RBS)",
    "DiagTestType": "SNG",
    "ReportingPriority": 3,
    "Notes": "Third hour check",
    "BranchID": 1,
    "DepartmentID": 10,
    "CreatedStaffID": "1",
    "CreatedDateTime": "2024-04-24 10:30:00",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2024-04-24 10:30:00",
    "IsRowDeleted": "N"
  },
  {
    "ID": 10097,
    "DiagGroupID": 3,
    "DiagGroupName": "GTT / OGTT(2 Hrs Oral Glucose Tolurence Test)",
    "DiagTestID": 1,
    "DiagTestName": "1 Time GRBS (Glucometer RBS)",
    "DiagTestType": "SNG",
    "ReportingPriority": 1,
    "Notes": "",
    "BranchID": 1,
    "DepartmentID": 11,
    "CreatedStaffID": "1",
    "CreatedDateTime": "2024-04-24 11:00:00",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2024-04-24 11:00:00",
    "IsRowDeleted": "N"
  },
  {
    "ID": 10098,
    "DiagGroupID": 3,
    "DiagGroupName": "GTT / OGTT(2 Hrs Oral Glucose Tolurence Test)",
    "DiagTestID": 5,
    "DiagTestName": "24 Hours Urine Creatinine",
    "DiagTestType": "SNG",
    "ReportingPriority": 2,
    "Notes": "",
    "BranchID": 1,
    "DepartmentID": 11,
    "CreatedStaffID": "1",
    "CreatedDateTime": "2024-04-24 11:00:00",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2024-04-24 11:00:00",
    "IsRowDeleted": "N"
  },
  {
    "ID": 10099,
    "DiagGroupID": 500,
    "DiagGroupName": "Lipid Profile",
    "DiagTestID": 502,
    "DiagTestName": "Total Cholesterol",
    "DiagTestType": "SNG",
    "ReportingPriority": 1,
    "Notes": "",
    "BranchID": 1,
    "DepartmentID": 10,
    "IsRowDeleted": "N"
  },
  {
    "ID": 10100,
    "DiagGroupID": 500,
    "DiagGroupName": "Lipid Profile",
    "DiagTestID": 503,
    "DiagTestName": "Triglycerides",
    "DiagTestType": "SNG",
    "ReportingPriority": 2,
    "Notes": "",
    "BranchID": 1,
    "DepartmentID": 10,
    "IsRowDeleted": "N"
  },
  {
    "ID": 10101,
    "DiagGroupID": 500,
    "DiagGroupName": "Lipid Profile",
    "DiagTestID": 504,
    "DiagTestName": "HDL Cholesterol",
    "DiagTestType": "SNG",
    "ReportingPriority": 3,
    "Notes": "",
    "BranchID": 1,
    "IsRowDeleted": "N"
  },
  {
    "ID": 10102,
    "DiagGroupID": 506,
    "DiagGroupName": "Diabetic Profile",
    "DiagTestID": 11,
    "DiagTestName": "Acid Phosphatase",
    "DiagTestType": "SNG",
    "ReportingPriority": 1,
    "Notes": "",
    "BranchID": 1,
    "DepartmentID": 10,
    "IsRowDeleted": "N"
  },
  {
    "ID": 10103,
    "DiagGroupID": 506,
    "DiagGroupName": "Diabetic Profile",
    "DiagTestID": 10,
    "DiagTestName": "A/G Ratio",
    "DiagTestType": "SNG",
    "ReportingPriority": 2,
    "Notes": "",
    "BranchID": 1,
    "DepartmentID": 10,
    "IsRowDeleted": "N"
  },
  {
    "ID": 10104,
    "DiagGroupID": 500,
    "DiagGroupName": "Lipid Profile",
    "DiagTestID": 506,
    "DiagTestName": "Diabetic Profile",
    "DiagTestType": "PRO",
    "ReportingPriority": 4,
    "Notes": "Nested profile",
    "BranchID": 1,
    "DepartmentID": 10,
    "IsRowDeleted": "N"
  },
  {
    "ID": 10105,
    "DiagGroupID": 505,
    "DiagGroupName": "Cardiac Profile",
    "DiagTestID": 508,
    "DiagTestName": "Troponin I",
    "DiagTestType": "SNG",
    "ReportingPriority": 1,
    "Notes": "",
    "BranchID": 1,
    "DepartmentID": 10,
    "IsRowDeleted": "N"
  },
  {
    "ID": 10106,
    "DiagGroupID": 505,
    "DiagGroupName": "Cardiac Profile",
    "DiagTestID": 509,
    "DiagTestName": "CPK-MB",
    "DiagTestType": "SNG",
    "ReportingPriority": 2,
    "Notes": "",
    "BranchID": 1,
    "DepartmentID": 10,
    "IsRowDeleted": "N"
  },
  {
    "ID": 10107,
    "DiagGroupID": 505,
    "DiagGroupName": "Cardiac Profile",
    "DiagTestID": 510,
    "DiagTestName": "NT-proBNP",
    "DiagTestType": "SNG",
    "ReportingPriority": 3,
    "Notes": "",
    "BranchID": 1,
    "DepartmentID": 10,
    "IsRowDeleted": "N"
  }
];

export const DIAG_TEST_DATA: any[] = [
  {
    "id": 1,
    "Code": "TST2335",
    "Name": "1 Time GRBS (Glucometer RBS)",
    "ShortName": "1 Time GRBS (Glucometer RBS)",
    "ReportName": "1 Time GRBS (Glucometer RBS)",
    "Type": "SNG",
    "SampleID": 0,
    "InstrumentName": "Minividas",
    "TestNameInInstrument": "",
    "ReportingPriority": 1000,
    "IsOutsourced": "Y",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 4,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Death",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": 757,
    "UpdatedDateTime": "2014-09-12 21:08:38",
    "IsRowDeleted": "Y",
    "InstrumentID": 1
  },
  {
    "id": 3,
    "Code": "TST2128",
    "Name": "GTT / OGTT(2 Hrs Oral Glucose Tolurence Test)",
    "ShortName": "GTT / OGTT (2 Hrs 75grms)",
    "ReportName": "Oral Glucose Tolurence Test (75 gms loded oral)",
    "Type": "PRO",
    "SampleID": null,
    "InstrumentName": "Minividas",
    "TestNameInInstrument": "",
    "ReportingPriority": 2,
    "IsOutsourced": "Y",
    "IsNABLApproved": "N",
    "Notes": " ",
    "Comments": "  ",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "",
    "DefaultReportData": "",
    "ReportAlign": "LeftAlign",
    "PageBreakNeeded": "NO",
    "BranchID": 1,
    "DepartmentID": "Cardiology",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": 757,
    "UpdatedDateTime": "0001-01-01 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 4,
    "Code": "TST2336",
    "Name": "2 Time GRBS (Glucometer RBS)",
    "ShortName": "2 Time GRBS",
    "ReportName": "Blood Sugar (GRBS)",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 21,
    "IsOutsourced": "Y",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Neurology",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": 757,
    "UpdatedDateTime": "2014-10-07 16:57:53",
    "IsRowDeleted": "Y",
    "InstrumentID": 1
  },
  {
    "id": 5,
    "Code": "TST2134",
    "Name": "24 Hours Urine Creatinine",
    "ShortName": "Urine Creatinine (24 Hrs)",
    "ReportName": "",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 106,
    "IsOutsourced": "Y",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Haematology",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2013-06-19 19:41:35",
    "IsRowDeleted": "N",
    "InstrumentID": 2
  },
  {
    "id": 6,
    "Code": "TST2166",
    "Name": "24 Hours Urine Metanephrines",
    "ShortName": "Urine Metanephrines (24 H",
    "ReportName": "",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 134,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Special",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Endocrinology",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2013-06-19 19:41:35",
    "IsRowDeleted": "N",
    "InstrumentID": 2
  },
  {
    "id": 8,
    "Code": "TST2129",
    "Name": "GTT / OGTT (3 Hrs Oral Glucose Tolerance Test",
    "ShortName": "GTT / OGTT (3 Hrs 100grms)",
    "ReportName": "Oral Glucose Tolerance Test (100 gms loded orale)",
    "Type": "PRO",
    "SampleID": null,
    "InstrumentName": "Minividas",
    "TestNameInInstrument": "",
    "ReportingPriority": 10000,
    "IsOutsourced": "Y",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "",
    "DefaultReportData": "",
    "ReportAlign": "LeftAlign",
    "PageBreakNeeded": "NO",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": 757,
    "UpdatedDateTime": "0001-01-01 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 9,
    "Code": "TST2337",
    "Name": "3 Time GRBS (Glucometer RBS)",
    "ShortName": "3 Time GRBS",
    "ReportName": "Blood Sugar (GRBS)",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 16,
    "IsOutsourced": "Y",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2013-06-19 19:41:35",
    "IsRowDeleted": "N",
    "InstrumentID": 2
  },
  {
    "id": 10,
    "Code": "TST2047",
    "Name": "A/G Ratio",
    "ShortName": "A/G Ratio",
    "ReportName": "",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 90,
    "IsOutsourced": "Y",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2013-06-19 19:41:35",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 11,
    "Code": "TST2049",
    "Name": "Acid Phosphatase",
    "ShortName": "ACP",
    "ReportName": "",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 92,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Special",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2013-06-19 19:41:35",
    "IsRowDeleted": "N",
    "InstrumentID": 2
  },
  {
    "id": 12,
    "Code": "TST2167",
    "Name": "ADA (Adenosine DE Aminase)",
    "ShortName": "ADA",
    "ReportName": "Adenosine Deaminase",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 135,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Special",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2013-06-19 19:41:35",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 13,
    "Code": "TST16",
    "Name": "Albumin",
    "ShortName": "Albumin",
    "ReportName": "",
    "Type": "SNG",
    "SampleID": 0,
    "InstrumentName": "BioChemistry",
    "TestNameInInstrument": "ALBUMIN",
    "ReportingPriority": 0,
    "IsOutsourced": "No",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 2,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": 757,
    "UpdatedDateTime": "2014-10-11 12:18:38",
    "IsRowDeleted": "N",
    "InstrumentID": 2
  },
  {
    "id": 14,
    "Code": "TST12",
    "Name": "Alkaline Phosphatase (ALP)",
    "ShortName": "ALP",
    "ReportName": "",
    "Type": "SNG",
    "SampleID": 0,
    "InstrumentName": "Minividas",
    "TestNameInInstrument": "ALP-AMP",
    "ReportingPriority": 29,
    "IsOutsourced": "Y",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 3,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": 757,
    "UpdatedDateTime": "2014-10-08 19:27:49",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 500,
    "Code": "PRO500",
    "Name": "Lipid Profile",
    "ShortName": "Lipid Prof",
    "ReportName": "Lipid Profile",
    "Type": "PRO",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 100,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 501,
    "Code": "MUL501",
    "Name": "Thyroid Profile (T3, T4, TSH)",
    "ShortName": "TFT",
    "ReportName": "Thyroid Function Test",
    "Type": "MUL",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 101,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 502,
    "Code": "SNG502",
    "Name": "Total Cholesterol",
    "ShortName": "T-Chol",
    "ReportName": "Total Cholesterol",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 102,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 503,
    "Code": "SNG503",
    "Name": "Triglycerides",
    "ShortName": "TGL",
    "ReportName": "Triglycerides",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 103,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 504,
    "Code": "SNG504",
    "Name": "HDL Cholesterol",
    "ShortName": "HDL",
    "ReportName": "HDL Cholesterol",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 104,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 505,
    "Code": "PRO505",
    "Name": "Cardiac Profile",
    "ShortName": "Cardiac",
    "ReportName": "Cardiac Profile",
    "Type": "PRO",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 105,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 506,
    "Code": "PRO506",
    "Name": "Diabetic Profile",
    "ShortName": "Diabetic",
    "ReportName": "Diabetic Profile",
    "Type": "PRO",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 106,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 507,
    "Code": "MUL507",
    "Name": "Renal Profile",
    "ShortName": "Renal",
    "ReportName": "Renal Function Profile",
    "Type": "MUL",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 107,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 508,
    "Code": "SNG508",
    "Name": "Troponin I",
    "ShortName": "TROP-I",
    "ReportName": "Troponin I",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 108,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 509,
    "Code": "SNG509",
    "Name": "CPK-MB",
    "ShortName": "CPK-MB",
    "ReportName": "CPK-MB",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 109,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 510,
    "Code": "SNG510",
    "Name": "NT-proBNP",
    "ShortName": "proBNP",
    "ReportName": "NT-proBNP",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 110,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": "1",
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": "1",
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 1100080,
    "Code": "RAD-SNG-1100080",
    "Name": "ANKLE AP & LATERAL VIEW 1F CR",
    "ShortName": "ANKLE AP & LATERAL",
    "ReportName": "ANKLE AP & LATERAL VIEW 1F CR",
    "Type": "SNG",
    "BranchID": 1,
    "DepartmentID": "Radiology",
    "Status": "Active"
  },
  {
    "id": 1100081,
    "Code": "RAD-SNG-1100081",
    "Name": "CHEST PA CR",
    "ShortName": "CHEST PA CR",
    "ReportName": "CHEST PA CR",
    "Type": "SNG",
    "BranchID": 1,
    "DepartmentID": "Radiology",
    "Status": "Active"
  },
  {
    "id": 1100082,
    "Code": "RAD-SNG-1100082",
    "Name": "CHEST DRAINAGE",
    "ShortName": "CHEST DRAINAGE",
    "ReportName": "CHEST DRAINAGE",
    "Type": "SNG",
    "BranchID": 1,
    "DepartmentID": "Radiology",
    "Status": "Active"
  },
  {
    "id": 1100083,
    "Code": "RAD-SNG-1100083",
    "Name": "UPPER GI ENDOSCOPY",
    "ShortName": "UPPER GI ENDOSCOPY",
    "ReportName": "UPPER GI ENDOSCOPY",
    "Type": "SNG",
    "BranchID": 1,
    "DepartmentID": "Radiology",
    "Status": "Active"
  },
  {
    "id": 1100084,
    "Code": "RAD-SNG-1100084",
    "Name": "CHEST AP/LAT 1F CR",
    "ShortName": "CHEST AP/LAT",
    "ReportName": "CHEST AP/LAT 1F CR",
    "Type": "SNG",
    "BranchID": 1,
    "DepartmentID": "Radiology",
    "Status": "Active"
  },
  {
    "id": 1100085,
    "Code": "RAD-SNG-1100085",
    "Name": "CHEST AP/LAT/OBLIQUE",
    "ShortName": "CHEST AP/LAT/OBLIQUE",
    "ReportName": "CHEST AP/LAT/OBLIQUE",
    "Type": "SNG",
    "BranchID": 1,
    "DepartmentID": "Radiology",
    "Status": "Active"
  },
  {
    "id": 1100086,
    "Code": "RAD-SNG-1100086",
    "Name": "CHEST LATRAL CR",
    "ShortName": "CHEST LATRAL",
    "ReportName": "CHEST LATRAL CR",
    "Type": "SNG",
    "BranchID": 1,
    "DepartmentID": "Radiology",
    "Status": "Active"
  },
  {
    "id": 1100087,
    "Code": "RAD-SNG-1100087",
    "Name": "CHEST PA VIEW 1F CR",
    "ShortName": "CHEST PA VIEW",
    "ReportName": "CHEST PA VIEW 1F CR",
    "Type": "SNG",
    "BranchID": 1,
    "DepartmentID": "Radiology",
    "Status": "Active"
  }
];

@Component({
  selector: 'app-test-group-list',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    LucideAngularModule,
    NgIcon,
    AsyncPipe,
    NgbPagination,
    NgbPaginationNext,
    NgbPaginationPrevious,
    NgbTooltipModule
  ],
  templateUrl: './test-group-list.component.html',
  providers: [TableService]
})
export class TestGroupListComponent implements OnInit {
  private router = inject(Router);
  protected readonly LucideSearch = LucideSearch;
  protected readonly LucideBox = LucideBox;
  protected readonly LucidePlus = LucidePlus;

  dateFilter = 'all';
  total$: Observable<number>;
  testGroups$: Observable<any[]>;

  constructor(public tableService: TableService<any>) {
    this.testGroups$ = this.tableService.items$;
    this.total$ = this.tableService.total$;
  }

  ngOnInit(): void {
    const filteredData = DIAG_TEST_DATA.filter(test =>
      ['MUL', 'PRO', 'PKG'].includes(test.Type)
    );
    this.tableService.setItems(filteredData, 10);
  }

  applyDateFilter() {
    this.tableService.setFilter('Type', this.dateFilter === 'all' ? '' : this.dateFilter);
  }

  addTestGroup() {
    this.router.navigate(['/master/diagnostic-lab/test-group-add']);
  }

  editTestGroup(id: number) {
    this.router.navigate(['/master/diagnostic-lab/test-group-edit', id]);
  }

  get hasSelection(): boolean {
    return this.tableService.hasSelectedItems();
  }

  deleteSelected() {
    if (confirm('Are you sure you want to delete selected items?')) {
      this.tableService.deleteSelectedItems();
    }
  }
}
