export const DEPARTMENT_LIST = [
  { id: 'DPT001', Name: 'Andrology', Description: 'Andrology', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT002', Name: 'Bio Chemistry', Description: 'Bio Chemistry', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT003', Name: 'Cardiology', Description: 'Cardiology', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'High' },
  { id: 'DPT004', Name: 'Clinical Pathology', Description: 'Clinical Pathology', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT005', Name: 'Cyto-Pathology', Description: 'Cyto-Pathology', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT006', Name: 'Gastroenterology', Description: 'Gastroenterology', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT007', Name: 'Haematology', Description: 'Haematology', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT008', Name: 'Histo-Pathology', Description: 'Histo-Pathology', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT009', Name: 'Microbiology', Description: 'Microbiology', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT010', Name: 'Radiology', Description: 'Radiology', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT011', Name: 'Serology', Description: 'Serology', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT012', Name: 'Anaesthetics', Description: 'Anaesthetics', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT013', Name: 'Diagnostic imaging (X-Ray)', Description: 'Diagnostic imaging (X-Ray)', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT014', Name: 'Ear nose and throat (ENT)', Description: 'Ear nose and throat (ENT)', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT015', Name: 'General surgery', Description: 'General surgery', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT016', Name: 'Gynaecology', Description: 'Gynaecology', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT017', Name: 'Nephrology', Description: 'Nephrology', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT018', Name: 'Neurology', Description: 'Neurology', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT019', Name: 'Nutrition and dietetics', Description: 'Nutrition and dietetics', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT020', Name: 'Obstetrics and gynaecology', Description: 'Obstetrics and gynaecology', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT021', Name: 'Oncology', Description: 'Oncology', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT022', Name: 'Ophthalmology', Description: 'Ophthalmology', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT024', Name: 'Physiotherapy', Description: 'Physiotherapy', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT025', Name: 'Radiotherapy', Description: 'Radiotherapy', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT026', Name: 'Rheumatology', Description: 'Rheumatology', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT027', Name: 'Urology', Description: 'Urology', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT028', Name: 'Pediatricians', Description: 'Pediatricians', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT029', Name: 'Physician', Description: 'Physician', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT030', Name: 'General Physician(Lady)', Description: 'General Physician(Lady)', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT031', Name: 'Phychaiatrist', Description: 'Phychaiatrist', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT032', Name: 'Dermatologist', Description: 'Dermatologist', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT033', Name: 'Plastic Surgeon', Description: 'Plastic Surgeon', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT034', Name: 'Homeopathy', Description: 'Homeopathy', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT035', Name: 'ENDOCRINOLOGY', Description: 'ENDOCRINOLOGY', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT036', Name: 'Maintenance', Description: 'Maintenance', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' },
  { id: 'DPT037', Name: 'Housekeeping', Description: 'Housekeeping', BranchName: 'Main Branch', ParentDepartment: '', ReportPriority: 'Normal' }
];
