export const STAFF_LIST = [
  {
    id: 'FLR001',
    FloorNumber: 'F01',
    FloorName: 'First Floor',
    HospitalBuildingName: 'Main Block',
    Accessibility: 'Wheelchair Accessible',
    FrontDeskPresent: 'Y',
    FrontDeskNumber: '101',
    FrontDeskStaffName: 'Meera Iyer',
    BranchName: 'Main Branch',
    Department: 'Clinical Pathology'
  },
  {
    id: 'FLR002',
    FloorNumber: 'F02',
    FloorName: 'Second Floor',
    HospitalBuildingName: 'Main Block',
    Accessibility: 'Standard',
    FrontDeskPresent: 'Y',
    FrontDeskNumber: '201',
    FrontDeskStaffName: 'Deepa Menon',
    BranchName: 'Main Branch',
    Department: 'Bio Chemistry'
  },
  {
    id: 'FLR003',
    FloorNumber: 'F03',
    FloorName: 'Third Floor',
    HospitalBuildingName: 'Main Block',
    Accessibility: 'Restricted',
    FrontDeskPresent: 'N',
    FrontDeskNumber: '',
    FrontDeskStaffName: '',
    BranchName: 'Main Branch',
    Department: 'Microbiology'
  },
  {
    id: 'FLR004',
    FloorNumber: 'G01',
    FloorName: 'Ground Floor',
    HospitalBuildingName: 'Annex Building',
    Accessibility: 'Full Access',
    FrontDeskPresent: 'Y',
    FrontDeskNumber: 'G01',
    FrontDeskStaffName: 'Sunita Reddy',
    BranchName: 'City Center Branch',
    Department: 'Radiology'
  },
  {
    id: 'FLR005',
    FloorNumber: 'B01',
    FloorName: 'Basement',
    HospitalBuildingName: 'Main Block',
    Accessibility: 'Ramp Access',
    FrontDeskPresent: 'N',
    FrontDeskNumber: '',
    FrontDeskStaffName: '',
    BranchName: 'Main Branch',
    Department: 'Maintenance'
  },
  {
    id: 'FLR006',
    FloorNumber: 'F04',
    FloorName: 'Fourth Floor',
    HospitalBuildingName: 'Main Block',
    Accessibility: 'Standard',
    FrontDeskPresent: 'Y',
    FrontDeskNumber: '401',
    FrontDeskStaffName: 'Anjali Sharma',
    BranchName: 'Main Branch',
    Department: 'Cardiology'
  },
  {
    id: 'FLR007',
    FloorNumber: 'F05',
    FloorName: 'Fifth Floor',
    HospitalBuildingName: 'Main Block',
    Accessibility: 'Standard',
    FrontDeskPresent: 'Y',
    FrontDeskNumber: '501',
    FrontDeskStaffName: 'Rahul Verma',
    BranchName: 'Main Branch',
    Department: 'Neurology'
  },
  {
    id: 'FLR008',
    FloorNumber: 'F06',
    FloorName: 'Sixth Floor',
    HospitalBuildingName: 'Specialty Wing',
    Accessibility: 'Restricted',
    FrontDeskPresent: 'N',
    FrontDeskNumber: '',
    FrontDeskStaffName: '',
    BranchName: 'Main Branch',
    Department: 'Oncology'
  },
  {
    id: 'FLR009',
    FloorNumber: 'G02',
    FloorName: 'Ground Floor B',
    HospitalBuildingName: 'Annex Building',
    Accessibility: 'Full Access',
    FrontDeskPresent: 'Y',
    FrontDeskNumber: 'G02',
    FrontDeskStaffName: 'Priya Das',
    BranchName: 'City Center Branch',
    Department: 'Physiotherapy'
  },
  {
    id: 'FLR010',
    FloorNumber: 'B02',
    FloorName: 'Lower Basement',
    HospitalBuildingName: 'Main Block',
    Accessibility: 'Staff Only',
    FrontDeskPresent: 'N',
    FrontDeskNumber: '',
    FrontDeskStaffName: '',
    BranchName: 'Main Branch',
    Department: 'Housekeeping'
  }
];
