export const STAFF_LIST = [
  {
    id: 'STF001',
    Name: 'Dr. Rajesh Kumar',
    Designation: 'Senior Pathologist',
    Department: 'Pathology',
    Status: 'Active',
    Gender: 'Male',
    Honorific: 'Dr',
    FirstName: 'Rajesh',
    LastName: 'Kumar',
    StaffNumber: 'EMP1001',
    DOB: '1980-05-15',
    MaritalStatus: 'Married',
    BloodGroup: 'O+',
    Nationality: 'Indian',
    Religion: 'Hindu',
    PhonePrimary: '+91 9876543210',
    EmergencyContactName: 'Anita Kumar',
    EmergencyContactRelationship: 'Spouse',
    DoctorPercentage: 15
  },
  {
    id: 'STF002',
    Name: 'Priya Sharma',
    Designation: 'Lab Technician',
    Department: 'Biochemistry',
    Status: 'Active',
    Gender: 'Female',
    Honorific: 'Ms',
    FirstName: 'Priya',
    LastName: 'Sharma',
    StaffNumber: 'EMP1002',
    DOB: '1992-08-22',
    MaritalStatus: 'Single',
    BloodGroup: 'A+',
    Nationality: 'Indian',
    Religion: 'Hindu',
    PhonePrimary: '+91 8765432109',
    EmergencyContactName: 'Suresh Sharma',
    EmergencyContactRelationship: 'Father',
    DoctorPercentage: 0
  },
  {
    id: 'STF003',
    Name: 'Dr. Amit Patel',
    Designation: 'Consultant Microbiologist',
    Department: 'Microbiology',
    Status: 'Active',
    Gender: 'Male',
    Honorific: 'Dr',
    FirstName: 'Amit',
    LastName: 'Patel',
    StaffNumber: 'EMP1003',
    DOB: '1975-12-10',
    MaritalStatus: 'Married',
    BloodGroup: 'B+',
    Nationality: 'Indian',
    Religion: 'Hindu',
    PhonePrimary: '+91 7654321098',
    EmergencyContactName: 'Meena Patel',
    EmergencyContactRelationship: 'Spouse',
    DoctorPercentage: 20
  },
  {
    id: 'STF004',
    Name: 'Sunita Reddy',
    Designation: 'Staff Nurse',
    Department: 'Nursing',
    Status: 'Active',
    Gender: 'Female',
    Honorific: 'Ms',
    FirstName: 'Sunita',
    LastName: 'Reddy',
    StaffNumber: 'EMP1004',
    DOB: '1988-03-05',
    MaritalStatus: 'Married',
    BloodGroup: 'AB+',
    Nationality: 'Indian',
    Religion: 'Hindu',
    PhonePrimary: '+91 6543210987',
    EmergencyContactName: 'Kiran Reddy',
    EmergencyContactRelationship: 'Spouse',
    DoctorPercentage: 0
  },
  {
    id: 'STF005',
    Name: 'Sanjay Gupta',
    Designation: 'Administrative Officer',
    Department: 'Administration',
    Status: 'Active',
    Gender: 'Male',
    Honorific: 'Mr',
    FirstName: 'Sanjay',
    LastName: 'Gupta',
    StaffNumber: 'EMP1005',
    DOB: '1982-11-20',
    MaritalStatus: 'Married',
    BloodGroup: 'O+',
    Nationality: 'Indian',
    Religion: 'Hindu',
    PhonePrimary: '+91 5432109876',
    EmergencyContactName: 'Deepak Gupta',
    EmergencyContactRelationship: 'Brother',
    DoctorPercentage: 0
  },
  {
    id: 'STF006',
    Name: 'Anjali Nair',
    Designation: 'Quality Manager',
    Department: 'Quality Assurance',
    Status: 'Active',
    Gender: 'Female',
    Honorific: 'Ms',
    FirstName: 'Anjali',
    LastName: 'Nair',
    StaffNumber: 'EMP1006',
    DOB: '1990-06-18',
    MaritalStatus: 'Single',
    BloodGroup: 'B-',
    Nationality: 'Indian',
    Religion: 'Hindu',
    PhonePrimary: '+91 4321098765',
    EmergencyContactName: 'Geetha Nair',
    EmergencyContactRelationship: 'Mother',
    DoctorPercentage: 0
  },
  {
    id: 'STF007',
    Name: 'Dr. Vikram Singh',
    Designation: 'Radiologist',
    Department: 'Radiology',
    Status: 'Active',
    Gender: 'Male',
    Honorific: 'Dr',
    FirstName: 'Vikram',
    LastName: 'Singh',
    StaffNumber: 'EMP1007',
    DOB: '1978-09-30',
    MaritalStatus: 'Married',
    BloodGroup: 'A+',
    Nationality: 'Indian',
    Religion: 'Sikh',
    PhonePrimary: '+91 3210987654',
    EmergencyContactName: 'Harpreet Kaur',
    EmergencyContactRelationship: 'Spouse',
    DoctorPercentage: 25
  },
  {
    id: 'STF008',
    Name: 'Meera Iyer',
    Designation: 'Receptionist',
    Department: 'Front Desk',
    Status: 'Active',
    Gender: 'Female',
    Honorific: 'Ms',
    FirstName: 'Meera',
    LastName: 'Iyer',
    StaffNumber: 'EMP1008',
    DOB: '1995-01-25',
    MaritalStatus: 'Single',
    BloodGroup: 'O+',
    Nationality: 'Indian',
    Religion: 'Hindu',
    PhonePrimary: '+91 2109876543',
    EmergencyContactName: 'Ravi Iyer',
    EmergencyContactRelationship: 'Father',
    DoctorPercentage: 0
  },
  {
    id: 'STF009',
    Name: 'Abdul Rahman',
    Designation: 'Accountant',
    Department: 'Finance',
    Status: 'Active',
    Gender: 'Male',
    Honorific: 'Mr',
    FirstName: 'Abdul',
    LastName: 'Rahman',
    StaffNumber: 'EMP1009',
    DOB: '1985-04-12',
    MaritalStatus: 'Married',
    BloodGroup: 'B+',
    Nationality: 'Indian',
    Religion: 'Muslim',
    PhonePrimary: '+91 1098765432',
    EmergencyContactName: 'Fatima Rahman',
    EmergencyContactRelationship: 'Spouse',
    DoctorPercentage: 0
  },
  {
    id: 'STF010',
    Name: 'Deepa Menon',
    Designation: 'Data Entry Operator',
    Department: 'IT',
    Status: 'Active',
    Gender: 'Female',
    Honorific: 'Ms',
    FirstName: 'Deepa',
    LastName: 'Menon',
    StaffNumber: 'EMP1010',
    DOB: '1993-07-08',
    MaritalStatus: 'Single',
    BloodGroup: 'A-',
    Nationality: 'Indian',
    Religion: 'Hindu',
    PhonePrimary: '+91 9988776655',
    EmergencyContactName: 'Madhavan Menon',
    EmergencyContactRelationship: 'Father',
    DoctorPercentage: 0
  }
];

export const HONORIFIC_LIST = ["Mr.", "Mrs.", "Ms.", "Baby", "Master", "Dr.", "Prof.", "Sir", "Major", "Lt..", "Baby of."];

export const DESIGNATION_LIST = [
  'Senior Pathologist',
  'Lab Technician',
  'Consultant Microbiologist',
  'Staff Nurse',
  'Administrative Officer',
  'Quality Manager',
  'Radiologist',
  'Receptionist',
  'Accountant',
  'Data Entry Operator'
];

export const DEPARTMENT_LIST = [
  'Pathology',
  'Biochemistry',
  'Microbiology',
  'Nursing',
  'Administration',
  'Quality Assurance',
  'Radiology',
  'Front Desk',
  'Finance',
  'IT'
];

export const STATUS_LIST = ['Active', 'Inactive'];
