import { Component, OnInit, inject } from '@angular/core';
import { CommonModule, AsyncPipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { LucideAngularModule, LucideBox, LucidePlus, LucideSearch } from 'lucide-angular';
import { NgbPagination, NgbPaginationNext, NgbPaginationPrevious, NgbTooltipModule } from '@ng-bootstrap/ng-bootstrap';
import { TableService } from '@core/services/table.service';
import { Router } from '@angular/router';
import { NgIcon } from '@ng-icons/core';
import { Observable } from 'rxjs';

export interface TestType {
  id: number;
  Code: string;
  Name: string;
  ShortName: string;
  ReportName: string;
  Type: string;
  IsOutsourced: string;
  [key: string]: any;
}

const TEST_DATA: TestType[] = [
  {
    "id": 1,
    "Code": "TST2335",
    "Name": "1 Time GRBS (Glucometer RBS)",
    "ShortName": "1 Time GRBS (Glucometer RBS)",
    "ReportName": "1 Time GRBS (Glucometer RBS)",
    "Type": "SNG",
    "SampleID": 0,
    "InstrumentName": "Minividas",
    "TestNameInInstrument": "",
    "ReportingPriority": 1000,
    "IsOutsourced": "Y",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 4,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Death",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": 757,
    "UpdatedDateTime": "2014-09-12 21:08:38",
    "IsRowDeleted": "Y",
    "InstrumentID": 1
  },
  {
    "id": 3,
    "Code": "TST2128",
    "Name": "GTT / OGTT(2 Hrs Oral Glucose Tolurence Test)",
    "ShortName": "GTT / OGTT (2 Hrs 75grms)",
    "ReportName": "Oral Glucose Tolurence Test (75 gms loded oral)",
    "Type": "PRO",
    "SampleID": null,
    "InstrumentName": "Minividas",
    "TestNameInInstrument": "",
    "ReportingPriority": 2,
    "IsOutsourced": "Y",
    "IsNABLApproved": "N",
    "Notes": " ",
    "Comments": "  ",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "",
    "DefaultReportData": "",
    "ReportAlign": "LeftAlign",
    "PageBreakNeeded": "NO",
    "BranchID": 1,
    "DepartmentID": "Cardiology",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": 757,
    "UpdatedDateTime": "0001-01-01 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 4,
    "Code": "TST2336",
    "Name": "2 Time GRBS (Glucometer RBS)",
    "ShortName": "2 Time GRBS",
    "ReportName": "Blood Sugar (GRBS)",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 21,
    "IsOutsourced": "Y",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Neurology",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": 757,
    "UpdatedDateTime": "2014-10-07 16:57:53",
    "IsRowDeleted": "Y",
    "InstrumentID": 1
  },
  {
    "id": 5,
    "Code": "TST2134",
    "Name": "24 Hours Urine Creatinine",
    "ShortName": "Urine Creatinine (24 Hrs)",
    "ReportName": "",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 106,
    "IsOutsourced": "Y",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Haematology",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": 1,
    "UpdatedDateTime": "2013-06-19 19:41:35",
    "IsRowDeleted": "N",
    "InstrumentID": 2
  },
  {
    "id": 6,
    "Code": "TST2166",
    "Name": "24 Hours Urine Metanephrines",
    "ShortName": "Urine Metanephrines (24 H",
    "ReportName": "",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 134,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Special",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Endocrinology",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": 1,
    "UpdatedDateTime": "2013-06-19 19:41:35",
    "IsRowDeleted": "N",
    "InstrumentID": 2
  },
  {
    "id": 8,
    "Code": "TST2129",
    "Name": "GTT / OGTT (3 Hrs Oral Glucose Tolerance Test",
    "ShortName": "GTT / OGTT (3 Hrs 100grms)",
    "ReportName": "Oral Glucose Tolerance Test (100 gms loded orale)",
    "Type": "PRO",
    "SampleID": null,
    "InstrumentName": "Minividas",
    "TestNameInInstrument": "",
    "ReportingPriority": 10000,
    "IsOutsourced": "Y",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "",
    "DefaultReportData": "",
    "ReportAlign": "LeftAlign",
    "PageBreakNeeded": "NO",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": 757,
    "UpdatedDateTime": "0001-01-01 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 9,
    "Code": "TST2337",
    "Name": "3 Time GRBS (Glucometer RBS)",
    "ShortName": "3 Time GRBS",
    "ReportName": "Blood Sugar (GRBS)",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 16,
    "IsOutsourced": "Y",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": 1,
    "UpdatedDateTime": "2013-06-19 19:41:35",
    "IsRowDeleted": "N",
    "InstrumentID": 2
  },
  {
    "id": 10,
    "Code": "TST2047",
    "Name": "A/G Ratio",
    "ShortName": "A/G Ratio",
    "ReportName": "",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 90,
    "IsOutsourced": "Y",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": 1,
    "UpdatedDateTime": "2013-06-19 19:41:35",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 11,
    "Code": "TST2049",
    "Name": "Acid Phosphatase",
    "ShortName": "ACP",
    "ReportName": "",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 92,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Special",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": 1,
    "UpdatedDateTime": "2013-06-19 19:41:35",
    "IsRowDeleted": "N",
    "InstrumentID": 2
  },
  {
    "id": 12,
    "Code": "TST2167",
    "Name": "ADA (Adenosine DE Aminase)",
    "ShortName": "ADA",
    "ReportName": "Adenosine Deaminase",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 135,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Special",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": 1,
    "UpdatedDateTime": "2013-06-19 19:41:35",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 13,
    "Code": "TST16",
    "Name": "Albumin",
    "ShortName": "Albumin",
    "ReportName": "",
    "Type": "SNG",
    "SampleID": 0,
    "InstrumentName": "BioChemistry",
    "TestNameInInstrument": "ALBUMIN",
    "ReportingPriority": 0,
    "IsOutsourced": "No",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 2,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": 757,
    "UpdatedDateTime": "2014-10-11 12:18:38",
    "IsRowDeleted": "N",
    "InstrumentID": 2
  },
  {
    "id": 14,
    "Code": "TST12",
    "Name": "Alkaline Phosphatase (ALP)",
    "ShortName": "ALP",
    "ReportName": "",
    "Type": "SNG",
    "SampleID": 0,
    "InstrumentName": "Minividas",
    "TestNameInInstrument": "ALP-AMP",
    "ReportingPriority": 29,
    "IsOutsourced": "Y",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 3,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2013-06-19 19:41:35",
    "UpdatedStaffID": 757,
    "UpdatedDateTime": "2014-10-08 19:27:49",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 500,
    "Code": "PRO500",
    "Name": "Lipid Profile",
    "ShortName": "Lipid Prof",
    "ReportName": "Lipid Profile",
    "Type": "PRO",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 100,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": 1,
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 501,
    "Code": "MUL501",
    "Name": "Thyroid Profile (T3, T4, TSH)",
    "ShortName": "TFT",
    "ReportName": "Thyroid Function Test",
    "Type": "MUL",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 101,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": 1,
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 502,
    "Code": "SNG502",
    "Name": "Total Cholesterol",
    "ShortName": "T-Chol",
    "ReportName": "Total Cholesterol",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 102,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": 1,
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 503,
    "Code": "SNG503",
    "Name": "Triglycerides",
    "ShortName": "TGL",
    "ReportName": "Triglycerides",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 103,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": 1,
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 504,
    "Code": "SNG504",
    "Name": "HDL Cholesterol",
    "ShortName": "HDL",
    "ReportName": "HDL Cholesterol",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 104,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": 1,
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 505,
    "Code": "PRO505",
    "Name": "Cardiac Profile",
    "ShortName": "Cardiac",
    "ReportName": "Cardiac Profile",
    "Type": "PRO",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 105,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": 1,
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 506,
    "Code": "PRO506",
    "Name": "Diabetic Profile",
    "ShortName": "Diabetic",
    "ReportName": "Diabetic Profile",
    "Type": "PRO",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 106,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": 1,
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 507,
    "Code": "MUL507",
    "Name": "Renal Profile",
    "ShortName": "Renal",
    "ReportName": "Renal Function Profile",
    "Type": "MUL",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 107,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": 1,
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 508,
    "Code": "SNG508",
    "Name": "Troponin I",
    "ShortName": "TROP-I",
    "ReportName": "Troponin I",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 108,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": 1,
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 509,
    "Code": "SNG509",
    "Name": "CPK-MB",
    "ShortName": "CPK-MB",
    "ReportName": "CPK-MB",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 109,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": 1,
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  },
  {
    "id": 510,
    "Code": "SNG510",
    "Name": "NT-proBNP",
    "ShortName": "proBNP",
    "ReportName": "NT-proBNP",
    "Type": "SNG",
    "SampleID": null,
    "InstrumentName": null,
    "TestNameInInstrument": "",
    "ReportingPriority": 110,
    "IsOutsourced": "N",
    "IsNABLApproved": "N",
    "Notes": "",
    "Comments": "",
    "Methodology": "",
    "Units": 0,
    "UnitID": null,
    "UnitName": null,
    "HasNormalRange": "N",
    "InvestigationType": "Routine",
    "ReportType": "Value",
    "DefaultReportData": "",
    "ReportAlign": "",
    "PageBreakNeeded": "",
    "BranchID": 1,
    "DepartmentID": "Bio Chemistry",
    "CreatedStaffID": 1,
    "CreatedDateTime": "2024-04-24 00:00:00",
    "UpdatedStaffID": 1,
    "UpdatedDateTime": "2024-04-24 00:00:00",
    "IsRowDeleted": "N",
    "InstrumentID": 1
  }
];

@Component({
  selector: 'app-test',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    LucideAngularModule,
    NgIcon,
    AsyncPipe,
    NgbPagination,
    NgbPaginationNext,
    NgbPaginationPrevious,
    NgbTooltipModule
  ],
  templateUrl: './test.component.html',
  providers: [TableService]
})
export class TestComponent implements OnInit {
  private router = inject(Router);
  protected readonly LucideSearch = LucideSearch;
  protected readonly LucideBox = LucideBox;
  protected readonly LucidePlus = LucidePlus;

  dateFilter = 'all';
  total$: Observable<number>;
  tests$: Observable<TestType[]>;

  constructor(public tableService: TableService<TestType>) {
    this.tests$ = this.tableService.items$;
    this.total$ = this.tableService.total$;
  }

  ngOnInit(): void {
    this.tableService.setItems(TEST_DATA, 10);
  }

  applyDateFilter() {
    this.tableService.setFilter('Type', this.dateFilter === 'all' ? '' : this.dateFilter);
  }

  addTest() {
    this.router.navigate(['/master/diagnostic-lab/test-new']);
  }

  editTest(id: number) {
    this.router.navigate(['/master/diagnostic-lab/test-new'], { queryParams: { id: id } });
  }

  get hasSelection(): boolean {
    return this.tableService.hasSelectedItems();
  }

  deleteSelected() {
    if (confirm('Are you sure you want to delete selected items?')) {
      this.tableService.deleteSelectedItems();
    }
  }
}
