import {ProductType} from '@/app/pages/masters/diagtests/types';

export const products: ProductType[] = [
    {
  id: 1,
  Code: "TST2335",
  Name: "1 Time GRBS (Glucometer RBS)",
  ShortName: "1 Time GRBS (Glucometer RBS)",
  ReportName: "1 Time GRBS (Glucometer RBS)",
  Type: "SNG",
  SampleID: 0,
  InstrumentName: "Minividas",
  TestNameInInstrument: "",
  ReportingPriority: 1000,
  IsOutsourced: "Y",
  IsNABLApproved: "N",
  Notes: "",
  Comments: "",
  Methodology: "",
  Units: 4,
  UnitID: null,
  UnitName: null,
  HasNormalRange: "N",
  InvestigationType: "Death",
  ReportType: "Value",
  DefaultReportData: "",
  ReportAlign: "",
  PageBreakNeeded: "",
  BranchID: 1,
  DepartmentID: 1,
  CreatedStaffID: 1,
  CreatedDateTime: "2013-06-19 19:41:35",
  UpdatedStaffID: 757,
  UpdatedDateTime: "2014-09-12 21:08:38",
  IsRowDeleted: "Y",
  InstrumentID: 1
},
{
  id: 3,
  Code: "TST2128",
  Name: "GTT / OGTT(2 Hrs Oral Glucose Tolurence Test)",
  ShortName: "GTT / OGTT (2 Hrs 75grms)",
  ReportName: "Oral Glucose Tolurence Test (75 gms loded oral)",
  Type: "PRO",
  SampleID: null,
  InstrumentName: "Minividas",
  TestNameInInstrument: "",
  ReportingPriority: 2,
  IsOutsourced: "Y",
  IsNABLApproved: "N",
  Notes: " ",
  Comments: "  ",
  Methodology: "",
  Units: 0,
  UnitID: null,
  UnitName: null,
  HasNormalRange: "N",
  InvestigationType: "Routine",
  ReportType: "",
  DefaultReportData: "",
  ReportAlign: "LeftAlign",
  PageBreakNeeded: "NO",
  BranchID: 1,
  DepartmentID: 1,
  CreatedStaffID: 1,
  CreatedDateTime: "2013-06-19 19:41:35",
  UpdatedStaffID: 757,
  UpdatedDateTime: "0001-01-01 00:00:00",
  IsRowDeleted: "N",
  InstrumentID: 1
},
{
  id: 4,
  Code: "TST2336",
  Name: "2 Time GRBS (Glucometer RBS)",
  ShortName: "2 Time GRBS",
  ReportName: "Blood Sugar (GRBS)",
  Type: "SNG",
  SampleID: null,
  InstrumentName: null,
  TestNameInInstrument: "",
  ReportingPriority: 21,
  IsOutsourced: "Y",
  IsNABLApproved: "N",
  Notes: "",
  Comments: "",
  Methodology: "",
  Units: 0,
  UnitID: null,
  UnitName: null,
  HasNormalRange: "N",
  InvestigationType: "Routine",
  ReportType: "",
  DefaultReportData: "",
  ReportAlign: "",
  PageBreakNeeded: "",
  BranchID: 1,
  DepartmentID: 1,
  CreatedStaffID: 1,
  CreatedDateTime: "2013-06-19 19:41:35",
  UpdatedStaffID: 757,
  UpdatedDateTime: "2014-10-07 16:57:53",
  IsRowDeleted: "Y",
  InstrumentID: 1
},
{
  id: 5,
  Code: "TST2134",
  Name: "24 Hours Urine Creatinine",
  ShortName: "Urine Creatinine (24 Hrs)",
  ReportName: "",
  Type: "SNG",
  SampleID: null,
  InstrumentName: null,
  TestNameInInstrument: "",
  ReportingPriority: 106,
  IsOutsourced: "Y",
  IsNABLApproved: "N",
  Notes: "",
  Comments: "",
  Methodology: "",
  Units: 0,
  UnitID: null,
  UnitName: null,
  HasNormalRange: "N",
  InvestigationType: "Routine",
  ReportType: "Value",
  DefaultReportData: "",
  ReportAlign: "",
  PageBreakNeeded: "",
  BranchID: 1,
  DepartmentID: 1,
  CreatedStaffID: 1,
  CreatedDateTime: "2013-06-19 19:41:35",
  UpdatedStaffID: 1,
  UpdatedDateTime: "2013-06-19 19:41:35",
  IsRowDeleted: "N",
  InstrumentID: 2
},
{
    id: 6,
    Code: "TST2166",
    Name: "24 Hours Urine Metanephrines",
    ShortName: "Urine Metanephrines (24 H",
    ReportName: "",
    Type: "SNG",
    SampleID: null,
    InstrumentName: null,
    TestNameInInstrument: "",
    ReportingPriority: 134,
    IsOutsourced: "N",
    IsNABLApproved: "N",
    Notes: "",
    Comments: "",
    Methodology: "",
    Units: 0,
    UnitID: null,
    UnitName: null,
    HasNormalRange: "N",
    InvestigationType: "Special",
    ReportType: "Value",
    DefaultReportData: "",
    ReportAlign: "",
    PageBreakNeeded: "",
    BranchID: 1,
    DepartmentID: 1,
    CreatedStaffID: 1,
    CreatedDateTime: "2013-06-19 19:41:35",
    UpdatedStaffID: 1,
    UpdatedDateTime: "2013-06-19 19:41:35",
    IsRowDeleted: "N",
    InstrumentID: 2
  },
  {
    id: 8,
    Code: "TST2129",
    Name: "GTT / OGTT (3 Hrs Oral Glucose Tolerance Test",
    ShortName: "GTT / OGTT (3 Hrs 100grms)",
    ReportName: "Oral Glucose Tolerance Test (100 gms loded orale)",
    Type: "PRO",
    SampleID: null,
    InstrumentName: "Minividas",
    TestNameInInstrument: "",
    ReportingPriority: 10000,
    IsOutsourced: "Y",
    IsNABLApproved: "N",
    Notes: "",
    Comments: "",
    Methodology: "",
    Units: 0,
    UnitID: null,
    UnitName: null,
    HasNormalRange: "N",
    InvestigationType: "Routine",
    ReportType: "",
    DefaultReportData: "",
    ReportAlign: "LeftAlign",
    PageBreakNeeded: "NO",
    BranchID: 1,
    DepartmentID: 1,
    CreatedStaffID: 1,
    CreatedDateTime: "2013-06-19 19:41:35",
    UpdatedStaffID: 757,
    UpdatedDateTime: "0001-01-01 00:00:00",
    IsRowDeleted: "N",
    InstrumentID: 1
  },
  {
    id: 9,
    Code: "TST2337",
    Name: "3 Time GRBS (Glucometer RBS)",
    ShortName: "3 Time GRBS",
    ReportName: "Blood Sugar (GRBS)",
    Type: "SNG",
    SampleID: null,
    InstrumentName: null,
    TestNameInInstrument: "",
    ReportingPriority: 16,
    IsOutsourced: "Y",
    IsNABLApproved: "N",
    Notes: "",
    Comments: "",
    Methodology: "",
    Units: 0,
    UnitID: null,
    UnitName: null,
    HasNormalRange: "N",
    InvestigationType: "Routine",
    ReportType: "",
    DefaultReportData: "",
    ReportAlign: "",
    PageBreakNeeded: "",
    BranchID: 1,
    DepartmentID: 1,
    CreatedStaffID: 1,
    CreatedDateTime: "2013-06-19 19:41:35",
    UpdatedStaffID: 1,
    UpdatedDateTime: "2013-06-19 19:41:35",
    IsRowDeleted: "N",
    InstrumentID: 2
  },
  {
    id: 10,
    Code: "TST2047",
    Name: "A/G Ratio",
    ShortName: "A/G Ratio",
    ReportName: "",
    Type: "SNG",
    SampleID: null,
    InstrumentName: null,
    TestNameInInstrument: "",
    ReportingPriority: 90,
    IsOutsourced: "Y",
    IsNABLApproved: "N",
    Notes: "",
    Comments: "",
    Methodology: "",
    Units: 0,
    UnitID: null,
    UnitName: null,
    HasNormalRange: "N",
    InvestigationType: "Routine",
    ReportType: "Value",
    DefaultReportData: "",
    ReportAlign: "",
    PageBreakNeeded: "",
    BranchID: 1,
    DepartmentID: 1,
    CreatedStaffID: 1,
    CreatedDateTime: "2013-06-19 19:41:35",
    UpdatedStaffID: 1,
    UpdatedDateTime: "2013-06-19 19:41:35",
    IsRowDeleted: "N",
    InstrumentID: 1
  },
  {
    id: 11,
    Code: "TST2049",
    Name: "Acid Phosphatase",
    ShortName: "ACP",
    ReportName: "",
    Type: "SNG",
    SampleID: null,
    InstrumentName: null,
    TestNameInInstrument: "",
    ReportingPriority: 92,
    IsOutsourced: "N",
    IsNABLApproved: "N",
    Notes: "",
    Comments: "",
    Methodology: "",
    Units: 0,
    UnitID: null,
    UnitName: null,
    HasNormalRange: "N",
    InvestigationType: "Special",
    ReportType: "Value",
    DefaultReportData: "",
    ReportAlign: "",
    PageBreakNeeded: "",
    BranchID: 1,
    DepartmentID: 1,
    CreatedStaffID: 1,
    CreatedDateTime: "2013-06-19 19:41:35",
    UpdatedStaffID: 1,
    UpdatedDateTime: "2013-06-19 19:41:35",
    IsRowDeleted: "N",
    InstrumentID: 2
  },
  {
    id: 12,
    Code: "TST2167",
    Name: "ADA (Adenosine DE Aminase)",
    ShortName: "ADA",
    ReportName: "Adenosine Deaminase",
    Type: "SNG",
    SampleID: null,
    InstrumentName: null,
    TestNameInInstrument: "",
    ReportingPriority: 135,
    IsOutsourced: "N",
    IsNABLApproved: "N",
    Notes: "",
    Comments: "",
    Methodology: "",
    Units: 0,
    UnitID: null,
    UnitName: null,
    HasNormalRange: "N",
    InvestigationType: "Special",
    ReportType: "Value",
    DefaultReportData: "",
    ReportAlign: "",
    PageBreakNeeded: "",
    BranchID: 1,
    DepartmentID: 1,
    CreatedStaffID: 1,
    CreatedDateTime: "2013-06-19 19:41:35",
    UpdatedStaffID: 1,
    UpdatedDateTime: "2013-06-19 19:41:35",
    IsRowDeleted: "N",
    InstrumentID: 1
  },
  {
    id: 13,
    Code: "TST16",
    Name: "Albumin",
    ShortName: "Albumin",
    ReportName: "",
    Type: "SNG",
    SampleID: 0,
    InstrumentName: "BioChemistry",
    TestNameInInstrument: "ALBUMIN",
    ReportingPriority: 0,
    IsOutsourced: "No",
    IsNABLApproved: "N",
    Notes: "",
    Comments: "",
    Methodology: "",
    Units: 2,
    UnitID: null,
    UnitName: null,
    HasNormalRange: "N",
    InvestigationType: "Routine",
    ReportType: "Value",
    DefaultReportData: "",
    ReportAlign: "",
    PageBreakNeeded: "",
    BranchID: 1,
    DepartmentID: 1,
    CreatedStaffID: 1,
    CreatedDateTime: "2013-06-19 19:41:35",
    UpdatedStaffID: 757,
    UpdatedDateTime: "2014-10-11 12:18:38",
    IsRowDeleted: "N",
    InstrumentID: 2
  },
  {
    id: 14,
    Code: "TST12",
    Name: "Alkaline Phosphatase (ALP)",
    ShortName: "ALP",
    ReportName: "",
    Type: "SNG",
    SampleID: 0,
    InstrumentName: "Minividas",
    TestNameInInstrument: "ALP-AMP",
    ReportingPriority: 29,
    IsOutsourced: "Y",
    IsNABLApproved: "N",
    Notes: "",
    Comments: "",
    Methodology: "",
    Units: 3,
    UnitID: null,
    UnitName: null,
    HasNormalRange: "N",
    InvestigationType: "Routine",
    ReportType: "Value",
    DefaultReportData: "",
    ReportAlign: "",
    PageBreakNeeded: "",
    BranchID: 1,
    DepartmentID: 1,
    CreatedStaffID: 1,
    CreatedDateTime: "2013-06-19 19:41:35",
    UpdatedStaffID: 757,
    UpdatedDateTime: "2014-10-08 19:27:49",
    IsRowDeleted: "N",
    InstrumentID: 1
  }
];

// export const products: ProductType[] = [
//     {
//         id: 1,
//         image: 'assets/images/products/1.png',
//         discount: 15,
//         name: 'Modern Minimalist Fabric Sofa Single Seater',
//         manufacturer: 'My Furniture',
//         category: 'Electronics',
//         sku: 'WB-10245',
//         stock: 56,
//         price: 59.99,
//         sellPrice: 44.99,
//         orders: 124,
//         rating: 5,
//         reviews: 87,
//         status: 'published',
//         date: '18 Apr, 2025',
//         time: '12:24 PM',
//     },
//     {
//         id: 2,
//         image: 'assets/images/products/2.png',
//         name: 'Funky Streetwear Sneakers - Neon Splash',
//         discount: 25,
//         manufacturer: 'BrightLite',
//         category: 'Home & Office',
//         sku: 'SL-89012',
//         stock: 32,
//         price: 899.0,
//         sellPrice: 678.15,
//         orders: 78,
//         rating: 4,
//         reviews: 54,
//         status: 'pending',
//         date: '22 Apr, 2025',
//         time: '09:45 AM',
//     },
//     {
//         id: 3,
//         image: 'assets/images/products/3.png',
//         discount: 15,
//         name: "Noise Canceling Wireless Earbuds - Black Edition",
//         manufacturer: 'ActiveWear Co.',
//         category: 'Fashion',
//         sku: 'RS-20450',
//         stock: 120,
//         price: 49.99,
//         sellPrice: 42.49,
//         orders: 231,
//         rating: 5,
//         reviews: 142,
//         status: 'published',
//         date: '24 Apr, 2025',
//         time: '03:10 PM',
//     },
//     {
//         id: 4,
//         image: 'assets/images/products/4.png',
//         name: 'Minimalist Solid Wood Dining Chair',
//         discount: 20,
//         manufacturer: 'FitPulse',
//         category: 'Fitness',
//         sku: 'FT-67123',
//         stock: 78,
//         price: 120.0,
//         sellPrice: 96.0,
//         orders: 198,
//         rating: 4,
//         reviews: 89,
//         status: 'published',
//         date: '23 Apr, 2025',
//         time: '10:12 AM',
//     },
//     {
//         id: 5,
//         image: 'assets/images/products/5.png',
//         name: 'Modern Black Minimalist Wall Clock',
//         discount: 20,
//         manufacturer: 'HyperClick',
//         category: 'Gaming',
//         sku: 'GM-72109',
//         stock: 120,
//         price: 49.99,
//         sellPrice: 39.99,
//         orders: 243,
//         rating: 3,
//         reviews: 102,
//         status: 'published',
//         date: '19 Apr, 2025',
//         time: '05:56 PM',
//     },
//     {
//         id: 6,
//         image: 'assets/images/products/6.png',
//         name: 'Elegant Brown Wooden Chair',
//         manufacturer: 'UrbanLiving',
//         discount: 20,
//         category: 'Furniture',
//         sku: 'FC-31220',
//         stock: 24,
//         price: 120.0,
//         sellPrice: 96.0,
//         orders: 38,
//         rating: 5,
//         reviews: 27,
//         status: 'out-of-stock',
//         date: '18 Apr, 2025',
//         time: '11:30 AM',
//     },
//     {
//         id: 7,
//         image: 'assets/images/products/7.png',
//         name: 'Apple iMac 24" Retina 4.5K Display',
//         discount: 20,
//         manufacturer: 'Softies',
//         category: 'Toys',
//         sku: 'TY-00788',
//         stock: 150,
//         price: 1299.0,
//         sellPrice: 1039.2,
//         orders: 305,
//         rating: 4,
//         reviews: 120,
//         status: 'published',
//         date: '17 Apr, 2025',
//         time: '04:21 PM',
//     },
//     {
//         id: 8,
//         image: 'assets/images/products/8.png',
//         name: 'Coolest Ergonomic Lounge Chair',
//         discount: 20,
//         manufacturer: 'ViewMaster',
//         category: 'Electronics',
//         sku: 'TV-5588',
//         stock: 64,
//         price: 320.0,
//         sellPrice: 256.0,
//         orders: 142,
//         rating: 4,
//         reviews: 88,
//         status: 'published',
//         date: '25 Apr, 2025',
//         time: '10:10 AM',
//     },
//     {
//         id: 9,
//         image: 'assets/images/products/9.png',
//         name: 'Apple iMac 24" M3',
//         manufacturer: 'Apple',
//         discount: 20,
//         category: 'Computers',
//         sku: 'IMAC-M3-24',
//         stock: 18,
//         price: 1399.00,
//         sellPrice: 1056.0,
//         orders: 29,
//         rating: 5,
//         reviews: 16,
//         status: 'pending',
//         date: '24 Apr, 2025',
//         time: '02:14 PM',
//     },
//     {
//         id: 10,
//         discount: 25,
//         image: 'assets/images/products/10.png',
//         name: 'Smart Watch Pro X2',
//         manufacturer: 'FitTech',
//         category: 'Wearables',
//         sku: 'SWPX2-GL',
//         stock: 85,
//         price: 149.50,
//         sellPrice: 110.0,
//         orders: 197,
//         rating: 4,
//         reviews: 65,
//         status: 'published',
//         date: '23 Apr, 2025',
//         time: '08:00 AM',
//     }
// ];
